version: '3.8'
services:
  nodered:
    image: nodered/node-red:latest-minimal
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data

volumes:
  node_red_data:
